#cloudbuild.yaml
# https://medium.com/@kevinsimper/building-docker-images-with-docker-compose-on-google-cloud-container-builder-292b1eb3fd31
steps:
- name: ‘docker/compose:1.19.0’
  args: [‘up’, ‘-d’]
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'workspace_app:latest', 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA']
  images: ['gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA']